// <auto-generated />
using Menu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMPS278Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221203175402_MenuItems")]
    partial class MenuItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("MenuItems.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cake Pops",
                            Description = "",
                            Name = "Chocolate Caramel",
                            Price = 50000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cake Pops",
                            Description = "",
                            Name = "Chocolate Caramel",
                            Price = 50000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cake Pops",
                            Description = "",
                            Name = "Chocolate Caramel",
                            Price = 50000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
